deployment:
  tasks:
    - 'echo "===== cPanel Hello World deploy: $(date) ====="'
    - 'mkdir -p /home/techaren/public_html/deploy-tests'
    - |
      echo "Hello from cPanel deploy at $(date)
      Branch: $(git rev-parse --abbrev-ref HEAD)
      Commit: $(git rev-parse --short HEAD)" \
      > /home/techaren/public_html/deploy-tests/hello.txt
