deployment:
  tasks:
    - 'set -euxo pipefail'

    # Context
    - 'echo "===== cPanel deploy: $(date) ====="'
    - 'echo "PWD: $PWD"'
    - 'echo "USER: $(whoami)"'
    - 'echo "BRANCH: $(git rev-parse --abbrev-ref HEAD || true)"'
    - 'echo "FILES AT REPO ROOT:"; ls -la'

    # Config
    - 'PYVER=3.10'
    - 'DEV_APP_ROOT=/home/kamranen/dev.backoffice'
    - 'PROD_APP_ROOT=/home/kamranen/backoffice'

    # Decide target by repo path
    - |
      case "$PWD" in
        */repositories/backoffice-dev)
          TARGET="$DEV_APP_ROOT"; ENV_NAME="dev"
          ;;
        */repositories/backoffice-prod)
          TARGET="$PROD_APP_ROOT"; ENV_NAME="prod"
          ;;
        *)
          echo "Unknown repo path ($PWD). Check cPanel repo path." >&2
          exit 1
          ;;
      esac
      echo "TARGET=$TARGET (env=$ENV_NAME)"

    # Sanity: show target dir existence and perms
    - 'echo "Target exists?"; if [ -d "$TARGET" ]; then echo "YES"; else echo "NO (will create)"; fi'
    - 'mkdir -p "$TARGET"'
    - 'echo "Target owner/perm:"; ls -ld "$TARGET"'

    # Write a marker file so we can see if we can write to TARGET
    - 'date > "$TARGET/DEPLOY_MARKER_$(date +%Y%m%d-%H%M%S).txt"'
    - 'echo "Wrote marker file. Listing TARGET:"; ls -la "$TARGET"'

    # Try rsync. If /bin/rsync missing on host, fall back to /usr/bin/rsync
    - 'RSYNC_BIN=$([ -x /bin/rsync ] && echo /bin/rsync || echo /usr/bin/rsync)'
    - 'echo "Using rsync at: $RSYNC_BIN"'
    - |
      "$RSYNC_BIN" -av --delete \
        --exclude ".git" \
        --exclude ".github" \
        --exclude ".cpanel.yml" \
        --exclude "__pycache__" \
        --exclude "node_modules" \
        --exclude "staticfiles" \
        --exclude "media" \
        ./ "$TARGET/"

    - 'echo "After rsync, TARGET listing:"; ls -la "$TARGET"'
    - 'echo "===== deploy finished ====="'
