# Generated by Django 5.2.5 on 2025-09-20 14:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialtxn',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount in PKR.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
