# Generated by Django 4.2.23 on 2025-08-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(choices=[('NET7', 'Net 7'), ('NET14', 'Net 14'), ('NET30', 'Net 30'), ('NET45', 'Net 45'), ('CASH', 'Cash'), ('Bank Transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='micron',
            field=models.CharField(max_length=10),
        ),
    ]
