# Generated by Django 5.2.5 on 2025-08-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('HBL', 'HBL'), ('MCB Bank', 'MCB Bank'), ('UBL', 'UBL'), ('National Bank of Pakistan (NBP)', 'National Bank of Pakistan (NBP)'), ('Allied Bank', 'Allied Bank'), ('Standard Chartered Bank Pakistan', 'Standard Chartered Bank Pakistan'), ('Bank Alfalah', 'Bank Alfalah'), ('Bank Al Habib', 'Bank Al Habib'), ('Meezan Bank', 'Meezan Bank'), ('Faysal Bank', 'Faysal Bank'), ('Habib Metropolitan Bank', 'Habib Metropolitan Bank'), ('Askari Bank', 'Askari Bank'), ('JS Bank', 'JS Bank'), ('Summit Bank', 'Summit Bank'), ('Sindh Bank', 'Sindh Bank'), ('The Bank of Punjab (BOP)', 'The Bank of Punjab (BOP)'), ('First Women Bank', 'First Women Bank'), ('Soneri Bank', 'Soneri Bank'), ('Silkbank', 'Silkbank'), ('Dubai Islamic Bank Pakistan', 'Dubai Islamic Bank Pakistan'), ('Al Baraka Bank', 'Al Baraka Bank'), ('Bank Islami Pakistan', 'Bank Islami Pakistan'), ('ICBC Pakistan', 'ICBC Pakistan'), ('Samba Bank', 'Samba Bank'), ('Zarai Taraqiati Bank Limited (ZTBL)', 'Zarai Taraqiati Bank Limited (ZTBL)'), ('Khushhali Microfinance Bank', 'Khushhali Microfinance Bank'), ('EasyPaisa', 'EasyPaisa'), ('JazzCash', 'JazzCash'), ('NayaPay', 'NayaPay'), ('SadaPay', 'SadaPay'), ('UPaisa', 'UPaisa'), ('HBL Konnect', 'HBL Konnect'), ('U Microfinance Bank', 'U Microfinance Bank'), ('Mobilink Microfinance Bank', 'Mobilink Microfinance Bank'), ('Telenor Microfinance Bank', 'Telenor Microfinance Bank')], max_length=50),
        ),
    ]
