# Generated by Django 5.2.5 on 2025-09-23 11:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rawmaterialtxn_amount_pkr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialtxn',
            name='qty_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
