# Generated by Django 4.2.23 on 2025-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_country_alter_order_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
