# Generated by Django 5.2.5 on 2025-08-31 09:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_notes_alter_customer_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'verbose_name': 'Payments Ledger', 'verbose_name_plural': 'Payments Ledger'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialpurchasepayment',
            options={'verbose_name': 'Purchase ↔ Supplier Payment Link', 'verbose_name_plural': 'Purchase ↔ Supplier Payment Links'},
        ),
        migrations.AddField(
            model_name='customer',
            name='pending_balance_pkr',
            field=models.IntegerField(default=0, help_text='Auto: carry + final orders − payments (int PKR).'),
        ),
        migrations.AddField(
            model_name='customermaterialledger',
            name='material_type',
            field=models.CharField(blank=True, choices=[('FILM', 'Film'), ('TAPE', 'Tape')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='previous_pending_balance_pkr',
            field=models.IntegerField(default=0, help_text='Initial carry-forward (once). In whole rupees.'),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.materialreceipt'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='TRANSFER', max_length=20)),
                ('bank', models.CharField(blank=True, choices=[('HBL', 'HBL'), ('MCB Bank', 'MCB Bank'), ('UBL', 'UBL'), ('National Bank of Pakistan (NBP)', 'National Bank of Pakistan (NBP)'), ('Allied Bank', 'Allied Bank'), ('Standard Chartered Bank Pakistan', 'Standard Chartered Bank Pakistan'), ('Bank Alfalah', 'Bank Alfalah'), ('Bank Al Habib', 'Bank Al Habib'), ('Meezan Bank', 'Meezan Bank'), ('Faysal Bank', 'Faysal Bank'), ('Habib Metropolitan Bank', 'Habib Metropolitan Bank'), ('Askari Bank', 'Askari Bank'), ('JS Bank', 'JS Bank'), ('Summit Bank', 'Summit Bank'), ('Sindh Bank', 'Sindh Bank'), ('The Bank of Punjab (BOP)', 'The Bank of Punjab (BOP)'), ('First Women Bank', 'First Women Bank'), ('Soneri Bank', 'Soneri Bank'), ('Silkbank', 'Silkbank'), ('Dubai Islamic Bank Pakistan', 'Dubai Islamic Bank Pakistan'), ('Al Baraka Bank', 'Al Baraka Bank'), ('Bank Islami Pakistan', 'Bank Islami Pakistan'), ('ICBC Pakistan', 'ICBC Pakistan'), ('Samba Bank', 'Samba Bank'), ('Zarai Taraqiati Bank Limited (ZTBL)', 'Zarai Taraqiati Bank Limited (ZTBL)'), ('Khushhali Microfinance Bank', 'Khushhali Microfinance Bank'), ('EasyPaisa', 'EasyPaisa'), ('JazzCash', 'JazzCash'), ('NayaPay', 'NayaPay'), ('SadaPay', 'SadaPay'), ('UPaisa', 'UPaisa'), ('HBL Konnect', 'HBL Konnect'), ('U Microfinance Bank', 'U Microfinance Bank'), ('Mobilink Microfinance Bank', 'Mobilink Microfinance Bank'), ('Telenor Microfinance Bank', 'Telenor Microfinance Bank')], max_length=50)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('amount_pkr', models.BigIntegerField(help_text='Whole PKR (no decimals).', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='rawmaterialpurchasepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_links', to='core.supplierpayment'),
        ),
    ]
