# Generated by Django 5.2.5 on 2025-09-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rawmaterialtxn_qty_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaterialledger',
            name='raw_txn',
            field=models.ForeignKey(blank=True, help_text='Backlink to raw-material transaction (for idempotent writes).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_rows', to='core.rawmaterialtxn'),
        ),
        migrations.AlterField(
            model_name='rawmaterialtxn',
            name='qty_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='customermaterialledger',
            constraint=models.UniqueConstraint(condition=models.Q(('raw_txn__isnull', False)), fields=('raw_txn', 'customer', 'type'), name='uniq_per_rawtxn_customer_type'),
        ),
    ]
