# Generated by Django 5.2.5 on 2025-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billing_and_raw_material_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreceipt',
            name='material_type',
            field=models.CharField(blank=True, choices=[('FILM', 'Film'), ('TAPE', 'Tape')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Please put any notes you want to include in bills in footer'),
        ),
    ]
