# Generated by Django 4.2.23 on 2025-08-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_payment_payment_method_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='payment_method',
        ),
    ]
