# Generated by Django 5.2.5 on 2025-09-10 10:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_materialreceipt_material_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='previous_material_balance_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Initial carry-forward of material (kg). Use negative if customer already owes material.', max_digits=12),
        ),
    ]
