# Generated by Django 5.2.5 on 2025-10-01 04:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customermaterialledger_raw_txn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='billing_theme',
            field=models.CharField(choices=[('default', 'Default (Detailed)'), ('compact_one_page', 'Compact One Page')], default='default', help_text='Choose the layout for invoices/statements', max_length=50),
        ),
        migrations.AlterField(
            model_name='rawmaterialtxn',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='Total amount in PKR.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rawmaterialtxn',
            name='rate_pkr',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='Rate per bag (PKR, can include decimals).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
