# Generated by Django 5.2.5 on 2025-09-10 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_previous_material_balance_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='previous_material_balance_kg',
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='is_opening_adjustment',
            field=models.BooleanField(default=False, help_text='Tick for one-time opening/correction. Allows negative kg and syncs to ledger as adjustment.'),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
