# Generated by Django 5.2.5 on 2025-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_billing_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='charge_negative_dana',
            field=models.BooleanField(blank=True, default=None, help_text='Override global toggle: True/False. Leave blank to use Site Settings.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='negative_dana_rate_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override rate (PKR/kg). Leave blank to use Site Settings.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_negative_dana_charges',
            field=models.BooleanField(default=False, help_text='If ON, negative (short) Dana in a billing period will be charged.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='negative_dana_default_rate_pkr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default rate (PKR per kg) used when a customer has a negative Dana.', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='negative_dana_label',
            field=models.CharField(default='Dana Minus', help_text="Label used on the invoice (e.g., 'Dana Minus').", max_length=64),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='billing_theme',
            field=models.CharField(choices=[('default', 'Default (Detailed)'), ('compact_one_page', 'Compact One Page')], default='default', help_text='Choose a template for invoices and monthly statements.', max_length=50),
        ),
    ]
