# Generated by Django 5.2.5 on 2025-11-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_charge_negative_dana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_cash_customer',
            field=models.BooleanField(default=False, help_text='Tick if this is a cash-only customer (no running credit balance).'),
        ),
        migrations.AddField(
            model_name='customer',
            name='show_material_on_statement',
            field=models.BooleanField(default=True, help_text='If unticked, hide Material Movements / Balance for this customer.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='show_payments_on_statement',
            field=models.BooleanField(default=True, help_text='If unticked, hide the Payments section for this customer.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='statement_theme',
            field=models.CharField(blank=True, choices=[('', 'Use global default'), ('default', 'Standard (multi-section)'), ('compact_one_page', 'Compact one-page')], default='', help_text='Override PDF layout for this customer only.', max_length=32),
        ),
    ]
