# Generated by Django 4.2.23 on 2025-08-15 02:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_status_materialreceipt_customermaterialledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='S.S Plastic', max_length=200)),
                ('company_address_lines', models.TextField(default='Plot #123, Industrial Street\nKarachi, Pakistan\nPhone: +92 300 1234567\nEmail: accounts@ssplastic.example', help_text='One line per row (will be printed at top of PDF).')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('tax_label', models.CharField(blank=True, default='GST', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('bank_details_lines', models.TextField(default='Bank: Meezan Bank\nAccount Name: S.S Plastic\nAccount Number: 0123456789\nIBAN: PK00MEZN000000123456789\nSWIFT: MEZNPKKA', help_text='One line per row (printed in PDF footer).')),
                ('email_backend', models.CharField(blank=True, default='', help_text='e.g. django.core.mail.backends.smtp.EmailBackend', max_length=200)),
                ('email_host', models.CharField(blank=True, default='', max_length=200)),
                ('email_port', models.PositiveIntegerField(blank=True, null=True)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200)),
                ('email_host_password', models.CharField(blank=True, default='', help_text='Consider env vars instead of storing here.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
