# Generated by Django 4.2.23 on 2025-08-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='bank_details_lines',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='company_address_lines',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
