# Generated by Django 4.2.23 on 2025-08-15 03:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_sitesettings_bank_details_lines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_size', models.CharField(max_length=50)),
                ('micron', models.CharField(help_text='Use syntax like 45/90 (not just a number).', max_length=20)),
                ('current_type', models.CharField(choices=[('NT', 'NT'), ('DT', 'DT'), ('ST', 'ST')], max_length=10)),
                ('target_total_kg', models.DecimalField(decimal_places=3, help_text='Requested kg for this category (e.g., 500.000)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('roll_weights_csv', models.TextField(blank=True, help_text='Comma-separated weights per roll (e.g., 12.5, 13, 10.75).')),
                ('tolerance_kg', models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Allowed difference between sum of rolls and target (kg)', max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
