# Generated by Django 4.2.23 on 2025-08-15 04:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='current_type',
            field=models.CharField(choices=[('NT', 'NT'), ('DT', 'DT'), ('ST', 'ST')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='micron',
            field=models.CharField(help_text='Use syntax like 45/90 (not just a number).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='roll_size',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='target_total_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='tolerance_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Allowed diff between produced and target at SHIPPED/CLOSED', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('NET7', 'Net 7'), ('NET14', 'Net 14'), ('NET30', 'Net 30'), ('NET45', 'Net 45'), ('CASH', 'Cash'), ('Bank Transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('INPROD', 'In Production'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped/Delivered'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12),
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.AddField(
            model_name='orderroll',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='core.order'),
        ),
    ]
