# Generated by Django 4.2.23 on 2025-08-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderroll_order_current_type_order_micron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='include_gst',
            field=models.BooleanField(default=True, help_text='Include GST for this order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
