# Generated by Django 4.2.23 on 2025-08-15 06:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_material_deducted_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermaterialledger',
            options={},
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='delta_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3),
        ),
        migrations.AddConstraint(
            model_name="customermaterialledger",
            constraint=models.UniqueConstraint(
                fields=("order", "type"),
                name="uniq_out_per_order",
                condition=models.Q(type="OUT"),   # <-- was entry_type
            ),
        )
    ]
