# Generated by Django 4.2.23 on 2025-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customermaterialledger_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customermaterialledger',
            name='uniq_out_per_order',
        ),
        migrations.AddConstraint(
            model_name='customermaterialledger',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'OUT')), fields=('order', 'type'), name='uniq_out_per_order'),
        ),
    ]
