# Generated by Django 4.2.23 on 2025-08-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_customermaterialledger_uniq_out_per_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customermaterialledger',
            name='uniq_out_per_order',
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_ledger_entries', to='core.order'),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.materialreceipt'),
        ),
        migrations.AddConstraint(
            model_name='customermaterialledger',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'OUT')), fields=('order', 'type'), name='uniq_out_per_order'),
        ),
    ]
