# Generated by Django 4.2.23 on 2025-08-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_customermaterialledger_uniq_out_per_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermaterialledger',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='customermaterialledger',
            name='uniq_out_per_order',
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='delta_kg',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materialreceipt'),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='type',
            field=models.CharField(choices=[('IN', 'Deposit'), ('OUT', 'Consumption')], max_length=3),
        ),
    ]
