# Generated by Django 4.2.23 on 2025-08-15 16:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_customermaterialledger_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermaterialledger',
            options={},
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='delta_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_ledger_entries', to='core.order'),
        ),
        migrations.AlterField(
            model_name='customermaterialledger',
            name='type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('INPROD', 'In Production'), ('READY', 'Ready for Shipping'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], default='DRAFT', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='customermaterialledger',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'OUT')), fields=('order', 'type'), name='uniq_out_per_order'),
        ),
    ]
