# Generated by Django 4.2.23 on 2025-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_customermaterialledger_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_challan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_challan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
