# Generated by Django 4.2.23 on 2025-08-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_delivery_challan_order_delivery_challan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_challan',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
