# Generated by Django 5.2.5 on 2025-08-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_order_delivery_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_challan',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
