# Generated by Django 5.2.5 on 2025-08-16 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_delivery_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='micron',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tolerance_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Allowed diff between produced and target at READY/DELIVERED/CLOSED', max_digits=6),
        ),
    ]
