# Generated by Django 5.2.5 on 2025-08-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_order_micron_alter_order_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='micron',
            field=models.CharField(help_text='Use syntax like 45/90 (not just a number).', max_length=20, null=True),
        ),
    ]
